MultiApps/urls.py
from django.contrib import admin
from django.urls import path, include

#readyToUse views-for-auth
from django.contrib.auth import views as auth_views

#from django.conf.urls import url


urlpatterns = [
    #home
    path('', include('home.urls')),

    path('admin/', admin.site.urls),

    #user-login, no imports
    path('accounts/', include('django.contrib.auth.urls')),

    #social-auth-app-django
    #path('oauth/', include('social_django.urls'), namespace='social'),

    #apps
    path('logger/', include('logger.urls')),
    path('todo/', include('todo.urls')),

]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()


# social-django-urls-added
'''
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using ',social_login,' as the login template')
except:
    print('Using registration/login.html as the login template')
'''

home/urls.py
from django.urls import path
from home.views import HomeView, ProfileView

app_name='home'

urlpatterns = [
	path('', HomeView.as_view(), name="index"),
	path('profile/', ProfileView.as_view(), name='profile'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class HomeView(View):
	def get(self, request):
			return render(request, 'home/index.html')

class ProfileView(LoginRequiredMixin, View):
	def get(self, request):
		user = request.user
		ctx={'user':user}
		return render(request, 'home/profile.html', ctx)

home/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="icon" href="{% static "favicon.ico" %}">
    <!--Font awesome 
    <script src="https://kit.fontawesome.com/687d560f4c.js" crossorigin="anonymous"></script>
    -->
    {% block head %}{% endblock head %}
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <!-- Image and text -->
    <nav class="navbar navbar-expand-md navbar-light border-bottom">
      <a class="navbar-brand" href="{% url 'home:index' %}">
        MultiApps
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url "home:profile" %}">Profile</a>
            <a class="nav-link" href="{% url "logout" %}?next={% url "home:index" %}" title="">Logout</a>
            <form class="form-inline my-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        {% else %}
            <a class="nav-link" href="{% url "login" %}?next={{ request.path }}">Login</a>
        {% endif %}
        </div>
      </div>
    </nav>

    <span class="float-left">
    {% if request %}
        <p>Path: <span class="text-monospace mark p-1">{{ request.path }}</span></p>
    {% else %}
        <p>No path!</p>
    {% endif %}
    </span>

    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    {% block footer %}
    {% endblock footer %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>