MultiApps/urls.py
from django.contrib import admin
from django.urls import path, include

#readyToUse views-for-auth
from django.contrib.auth import views as auth_views

#from django.conf.urls import url


urlpatterns = [
    #home
    path('', include('home.urls')),

    path('admin/', admin.site.urls),

    #user-login, no imports
    path('accounts/', include('django.contrib.auth.urls')),

    #social-auth-app-django
    #path('oauth/', include('social_django.urls'), namespace='social'),

    #apps
    path('logger/', include('logger.urls')),
    path('todo/', include('todo.urls')),

]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()


# social-django-urls-added
'''
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using ',social_login,' as the login template')
except:
    print('Using registration/login.html as the login template')
'''

home/urls.py
from django.urls import path
from home.views import HomeView, ProfileView

app_name='home'

urlpatterns = [
	path('', HomeView.as_view(), name="index"),
	path('profile/', ProfileView.as_view(), name='profile'),
]

logger/urls.py
from django.urls import path
from logger.views import *

app_name = 'logger'

urlpatterns = [
    #model- Topic
    path('', LogListView.as_view(), name='log_list'),
    path('log/<int:pk>', LogDetailView.as_view(), name='log_detail'),
    path('log/create', LogCreateView.as_view(), name='log_create'),
    path('log/<int:pk>/delete', LogDeleteView.as_view(), name='log_delete'),
    path('log/<int:pk>/update', LogUpdateView.as_view(), name='log_update'),

    #model- Board
    path('boards', BoardListView.as_view(), name='board_list'),
    path('board/<int:pk>', BoardDetailView.as_view(), name='board_detail'),
    path('board/create', BoardCreateView.as_view(), name='board_create'),
    path('board/<int:pk>/delete', BoardDeleteView.as_view(), name='board_delete'),
]

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns =[
	path("", views.TodoMain.as_view(), name="todo_main"),
	path("all-tasks", views.TaskListView.as_view(), name="task_list"),
	path("task/create/", views.TaskCreate.as_view(), name="task_create"),
	path("task/<int:pk>", views.TaskDetail.as_view(), name="task_detail"),
	path("task/<int:pk>/complete", views.StatusComplete.as_view(), name="status_complete"),
	path("task/<int:pk>/incomplete", views.StatusIncomplete.as_view(), name="status_incomplete"),
	path("task/<int:pk>/delete", views.TaskDelete.as_view(), name="task_delete"),

	path("task-group/", views.GroupView.as_view(), name="group_view"),
	path("task-group/create", views.GroupCreate.as_view(), name="group_create"),
	path("task-group/<int:pk>/delete", views.GroupDeleteView.as_view(), name="group_delete"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class HomeView(View):
	def get(self, request):
			return render(request, 'home/index.html')

class ProfileView(LoginRequiredMixin, View):
	def get(self, request):
		user = request.user
		ctx={'user':user}
		return render(request, 'home/profile.html', ctx)

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}MultiApps{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/logger.css'%}">
{% endblock head %}
{% block content %}
<div class="container m-5">
	<h4 class="display-4">All apps here:</h4>
	{% if not user.is_authenticated %}<p class="lead">You need to login to use some disabled apps:</p>{% endif %}
		<ul>
			<li><a class="text-decoration-none {% if not user.is_authenticated %}disabledapp{% endif %}" href="{% url "logger:log_list" %}" title="Logger">Logger</a> - Create your daily productivity logs. <span class="badge badge-primary">Complete CRUD app</span></li>
			<li><a class="text-decoration-none {% if not user.is_authenticated %}disabledapp{% endif %}" href="{% url 'todo:todo_main' %}" title="Todo">Todo</a>. <span class="badge badge-primary">todos for you</span></li>
		</ul>
</div>
{% endblock content %}

home/templates/home/profile.html
{% extends "base.html" %}

{% block content %}
	<div class="container m-5">
		<h1 class="display-4">Profile:</h1>
		<p>Username: {{ user }}</a></p>		
	</div>
{% endblock content %}