MultiApps/urls.py
from django.contrib import admin
from django.urls import path, include

#readyToUse views-for-auth
from django.contrib.auth import views as auth_views

#from django.conf.urls import url


urlpatterns = [
    #home
    path('', include('home.urls')),

    path('admin/', admin.site.urls),

    #user-login, no imports
    path('accounts/', include('django.contrib.auth.urls')),

    #social-auth-app-django
    #path('oauth/', include('social_django.urls'), namespace='social'),

    #apps
    path('logger/', include('logger.urls')),
    path('todo/', include('todo.urls')),

]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()


# social-django-urls-added
'''
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using ',social_login,' as the login template')
except:
    print('Using registration/login.html as the login template')
'''

home/urls.py
from django.urls import path
from home.views import HomeView, ProfileView

app_name='home'

urlpatterns = [
	path('', HomeView.as_view(), name="index"),
	path('profile/', ProfileView.as_view(), name='profile'),
]

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns =[
	path("", views.TodoMain.as_view(), name="todo_main"),
	path("all-tasks", views.TaskListView.as_view(), name="task_list"),
	path("task/create/", views.TaskCreate.as_view(), name="task_create"),
	path("task/<int:pk>", views.TaskDetail.as_view(), name="task_detail"),
	path("task/<int:pk>/complete", views.StatusComplete.as_view(), name="status_complete"),
	path("task/<int:pk>/incomplete", views.StatusIncomplete.as_view(), name="status_incomplete"),
	path("task/<int:pk>/delete", views.TaskDelete.as_view(), name="task_delete"),

	path("task-group/", views.GroupView.as_view(), name="group_view"),
	path("task-group/create", views.GroupCreate.as_view(), name="group_create"),
	path("task-group/<int:pk>/delete", views.GroupDeleteView.as_view(), name="group_delete"),
]

todo/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.
class TaskGroup(models.Model):
	name = models.CharField(max_length=128)
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	class Meta:
		ordering = ["name"]

	def __str__(self):
		return self.name

class Task(models.Model):
	title = models.CharField(max_length=256)
	text = models.TextField(blank=True, null=True)
	task_group = models.ForeignKey(TaskGroup, on_delete=models.CASCADE, null=True, blank=True)
	created_on = models.DateTimeField(auto_now_add=True)
	completed = models.BooleanField(default=False)
	creator = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		related_name="todo_created_by",
		on_delete=models.CASCADE,
	)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["completed","created_on"]

todo/forms.py
from django import forms
from todo.models import *

class TaskForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('users')
		super(TaskForm, self).__init__(*args, **kwargs)
		self.fields['task_group'].queryset = TaskGroup.objects.filter(creator=user)
	
	class Meta:
		model = Task
		fields=['title', 'text', 'task_group']

class GroupForm(forms.ModelForm):
	class Meta:
		model = TaskGroup
		fields=['name']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View

from home import owner
from todo.models import *
from todo.forms import *

#main page
class TodoMain(owner.OwnerView):
	template_name = "todo/todo.html"

	def get(self, request):
#		taskgroup = TaskGroup.objects.filter(creator=request.user)
		gc = TaskGroup.objects.filter(creator=request.user).count()
		rt = Task.objects.filter(creator=request.user).filter(completed=False)[:5]
		ctx={'groups_count':gc, 'recent_tasks':rt}
		return render(request, self.template_name, ctx)

# model: task

class TaskListView(owner.OwnerView):
	template_name = "todo/task_list.html"

	def get(self, request):
		tasks = Task.objects.filter(creator=request.user)
		ctx={'tasks':tasks}
		return render(request, self.template_name, ctx)

class TaskDetail(owner.OwnerView):
	template_name= "todo/task_detail.html"

	def get(self, request, pk):
		task = Task.objects.get(id=pk)
		ctx ={'task':task}
		return render(request, self.template_name, ctx)

class TaskCreate(owner.OwnerView):
	template_name = "todo/todo_form.html"
	success_url = reverse_lazy('todo:todo_main')

	def get(self, request, pk=None):
		tform = TaskForm(request.GET or None, users=request.user)
		ctx={'form':tform}
		return render(request, self.template_name, ctx)

	def post(self, request, pk=None):
		task = TaskForm(request.POST, users=request.user)
		frm = task.save(commit=False)
		frm.creator = request.user
		frm.save()
		return redirect(self.success_url)

class TaskDelete(owner.OwnerView):
	success_url = reverse_lazy('todo:todo_main')

	def post(self, request, pk):
		task = get_object_or_404(Task, id=pk)
		task.delete()
		try:
			return redirect(self.request.GET['next'])
		except:
			return redirect(self.success_url)

class StatusComplete(owner.OwnerView):
	success_url = reverse_lazy("todo:todo_main")
	def post(self, request, pk):
		task = get_object_or_404(Task, id=pk)
		task.completed = True
		task.save()
		try:
			return redirect(self.request.GET['next'])
		except:
			return redirect(self.success_url)

class StatusIncomplete(owner.OwnerView):
	success_url = reverse_lazy("todo:todo_main")
	def post(self, request, pk):
		task = get_object_or_404(Task, id=pk)
		task.completed = False
		task.save()
		try:
			return redirect(self.request.GET['next'])
		except:
			return redirect(self.success_url)

# model: TaskGroup
class GroupView(owner.OwnerView):
	template_name = "todo/group_view.html"

	def get(self, request):
		t = Task.objects.all().filter(creator=request.user).order_by('task_group__name')
		grps = TaskGroup.objects.filter(creator=request.user)
		form = GroupForm()
		ctx={'tasks':t, 'form':form, 'grps':grps}
		return render(request, self.template_name, ctx)

class GroupCreate(owner.OwnerView):
	success_url=reverse_lazy("todo:group_view")
	def post(self, request):
		grp = GroupForm(request.POST)
		group = grp.save(commit=False)
		group.creator = request.user
		group.save()
		try:
			return redirect(self.request.GET['next'])
		except:
			return redirect(self.success_url)

class GroupDeleteView(owner.OwnerView):
	success_url= reverse_lazy("todo:group_view")
	def post(self, request, pk):
		grp = get_object_or_404(TaskGroup, id=pk)
		grp.delete()
		try:
			return redirect(self.request.GET['next'])
		except:
			return redirect(self.success_url)

todo/templates/todo/group_view.html
{% extends "base.html" %} {% block content %}
<div class="container mt-5 m-sm-5">
	<a class="btn btn-primary" href="{% url 'todo:task_list' %}">Tasks</a>
	<a class="float-right text-decoration-none" href="{% url 'todo:todo_main' %}"
		>todos</a
	>

<!--AddGroup-toggle-button-->
	<button
		class="btn btn-warning"
		id="AddGroupButton"
		type="button"
		data-toggle="collapse"
		data-target="#AddEditGroup"
	>
		Add Group
	</button>

<!--DelGroup-toggle-button-->
	<button
		class="btn btn-danger"
		id="DelGroupButton"
		type="button"
		data-toggle="collapse"
		data-target="#DelGroup"
	>
		Delete Group
	</button>

<!--AddGroup-toggle-form start-->
	<div id="AddEditGroup" class="collapse">
		<form action="{% url 'todo:group_create' %}" method="post">
			<div class="form-group border m-3 p-3">
				{% csrf_token %}
				<label for="id_name">Name:</label>
				<input
					type="text"
					name="name"
					maxlength="128"
					required
					id="id_name"
					class="form-control"
				/>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
<!--Addgroup-toggle-form -End-->

<!--DeleteGroup-toggle-form start-->
	<div id="DelGroup" class="collapse">
		<ul class="list-group list-group-flush mt-2">
			{% for grp in grps %}
			<li class="list-group-item">
				{{ grp.name }}
				<form
					method="post"
					action="{% url 'todo:group_delete' grp.id %}?next={{request.path}}"
					role="form"
					class="float-right"
				>
					{% csrf_token %}
					<button
						class="btn btn-danger btn-sm"
						type="submit"
						name="submit_delete"
					>
						Delete
					</button>
				</form>
			</li>
			{% endfor %}
		</ul>
	</div>
<!--DelGroup-toggle-form End-->

	{% regroup tasks by task_group as groups %}
	<div class="row-cols-1">
		{% for group in groups %}
		<div class="col-md m-3">
			<a
				class="text-decoration-none"
				data-toggle="collapse"
				href="#{{group.grouper}}"
				role="button"
				aria-expanded="false"
				aria-controls="{{group.grouper}}"
			>
				<h3 class="text-dark">{{ group.grouper }}</h3>
			</a>
			<div class="collapse" id="{{group.grouper}}">
				<ul class="list-group list-group-flush border">
					{% for task in group.list %}
					<li class="list-group-item">
						<a
							class="text-decoration-none"
							href="{% url 'todo:task_detail' task.id %}"
							>{{ task }}</a
						>
						{% if task.completed %}
						<form
							method="post"
							action="{% url 'todo:task_delete' task.id %}?next={{request.path}}"
							role="form"
							class="float-right"
						>
							{% csrf_token %}
							<button
								class="btn btn-danger btn-sm"
								type="submit"
								name="submit_delete"
							>
								Delete
							</button>
						</form>
						<span class="badge badge-success">completed</span>
						{% else %}
						<span class="badge badge-danger">Not completed</span>
						{% endif %}
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock content %}

todo/templates/todo/task_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid mt-5">
	<a class="float-right text-decoration-none" href="{% url 'todo:todo_main' %}">todos</a>
	<a class="btn btn-primary" href="{% url 'todo:task_list' %}">Tasks</a>
	<a class="btn btn-warning" href="{% url 'todo:group_view' %}"
		>todo-groups</a>

	<div class="card-deck mt-2">
		<div class="card col-sm-9">
			<div class="card-body">
				<div class="card-title"><strong>{{ task }}</strong></div>
				<div class="card-text">{{ task.text }}</div>
			</div>
		</div>
		<div class="card col-sm-3">
			<ul class="list-group list-group-flush">
				{% if not task.completed%}
				<li class="list-group-item">
					<form
						method="post"
						action="{% url 'todo:status_complete' task.id %}?next={{ request.path }}"
						role="form" 
						class="d-inline"
					>
						{% csrf_token %}
						<button class="btn btn-info btn-sm m-1" type="submit">Done</button>
					</form>
				{% else %}
					<form
						method="post"
						action="{% url 'todo:status_incomplete' task.id %}"
						role="form" 
						class="d-inline"
					>
						{% csrf_token %}
						<button class="btn btn-info btn-sm m-1" type="submit">Not done</button>
					</form>
				{% endif %}
					<form
						method="post"
						action="{% url 'todo:task_delete' task.id %}?next={{ request.path }}"
						role="form"
						class="d-inline"
					>
						{% csrf_token %}
						<button
							class="btn btn-danger btn-sm m-1"
							type="submit"
							name="submit_delete"
						>
							Delete
						</button>
					</form>
				</li>
					<li class="list-group-item"><strong>Created on:</strong> <br>&nbsp;&nbsp;{{ task.created_on|date:"D, d M, Y" }}</li>
					<li class="list-group-item"><strong>Group:</strong><br>&nbsp;&nbsp;{{ task.task_group }}</li>
			</ul>
		</div>
	</div>
</div>
{% endblock content %}

todo/templates/todo/task_list.html
{% extends "base.html" %} {% block content %}
<div class="container mt-5">
	<a class="btn btn-warning" href="{% url 'todo:group_view' %}"
		>todo-groups</a>
		<a class="float-right text-decoration-none" href="{% url 'todo:todo_main' %}">todos</a>
	<table class="table mt-2">
		<thead>
    <tr>
      <th scope="col">task</th>
      <th scope="col">task-group</th>
      <th scope="col">Status</th>
      <th scope="col">Delete?</th>
    </tr>
  </thead>
		<tbody>
			{% for task in tasks %}
			<tr>
				<td class="">
					<a
						href="{% url 'todo:task_detail' task.id %}"
						class="text-decoration-none"
						>{{ task.title }}</a
					>
				</td>
				<td class="text-muted">{{ task.task_group }}</td>
				<td class="">
					{% if task.completed is False %}
					<form
						method="post"
						action="{% url 'todo:status_complete' task.id %}?next={{ request.path }}"
						role="form"
						class="d-inline"
					>
						{% csrf_token %}
						<button class="btn btn-warning btn-sm" type="submit">Not Completed</button>
					</form>
					{% else %}
					<form
						method="post"
						action="{% url 'todo:status_incomplete' task.id %}?next={{ request.path }}"
						role="form"
						class="d-inline"
					>
						{% csrf_token %}
						<button class="btn btn-success btn-sm" type="submit">Completed</button>
					</form>
					{% endif %}
				</td>
				<td>
					<form
						method="post"
						action="{% url 'todo:task_delete' task.id %}?next={{ request.path }}"
						role="form"
						class="d-inline"
					>
						{% csrf_token %}
						<button
							class="btn btn-danger btn-sm"
							type="submit"
							name="submit_delete"
						>
							Delete
						</button>
					</form>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock content %}

todo/templates/todo/todo.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/todo.css' %}" />
{% endblock head %}
{% block title %}Todo{% endblock title %}
{% block content%}
<div class="container mt-5 m-sm-5">
	<a class="btn btn-primary" href="{% url 'todo:task_create' %}">Add-task</a>
	<a class="btn btn-warning" href="{% url 'todo:group_view' %}"
		>todo-groups <span class="badge badge-dark">{{ groups_count }}</span>
	</a>
	<h1 class="display-1 text-center font-weight-bold todo">todos</h1>
	<p class="lead">Unfinished tasks:</p>
	<div>
		<ul class="container list-group list-group-flush">
			{% for task in recent_tasks %}
			<li class="list-group-item">
				<a
					class="col-8 text-decoration-none"
					href="{% url 'todo:task_detail' task.id %}"
					>{{ task }}</a
				>
				<div class="float-md-right">
					<form
						method="post"
						action="{% url 'todo:task_delete' task.id %}"
						role="form"
						class="d-inline"
					>
						{% csrf_token %}
						<div style="display: inline">
							<button
								class="btn btn-danger btn-sm"
								type="submit"
								name="submit_delete"
							>
								Delete
							</button>
						</div>
					</form>
					<form
						method="post"
						action="{% url 'todo:status_complete' task.id %}?next={{ request.path }}"
						role="form"
						class="d-inline"
					>
						{% csrf_token %}
						<button class="btn btn-info btn-sm m-1" type="submit">Done</button>
					</form>
				</div>
			</li>
			{% endfor %}
		</ul>
	</div>
	<a class="text-center" href="{% url 'todo:task_list' %}">All tasks</a>
</div>
{% endblock content %}

todo/templates/todo/todo_form.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit">
		<input type="submit" value="Cancel" 
		onclick="window.location='{% url 'todo:todo_main' %}'; return false;">
	</form>
</div>
{% endblock content %}