MultiApps/urls.py
from django.contrib import admin
from django.urls import path, include

#readyToUse views-for-auth
from django.contrib.auth import views as auth_views

#from django.conf.urls import url


urlpatterns = [
    #home
    path('', include('home.urls')),

    path('admin/', admin.site.urls),

    #user-login, no imports
    path('accounts/', include('django.contrib.auth.urls')),

    #social-auth-app-django
    #path('oauth/', include('social_django.urls'), namespace='social'),

    #apps
    path('logger/', include('logger.urls')),
    path('todo/', include('todo.urls')),

]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()


# social-django-urls-added
'''
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using ',social_login,' as the login template')
except:
    print('Using registration/login.html as the login template')
'''

home/urls.py
from django.urls import path
from home.views import HomeView, ProfileView

app_name='home'

urlpatterns = [
	path('', HomeView.as_view(), name="index"),
	path('profile/', ProfileView.as_view(), name='profile'),
]

logger/urls.py
from django.urls import path
from logger.views import *

app_name = 'logger'

urlpatterns = [
    #model- Topic
    path('', LogListView.as_view(), name='log_list'),
    path('log/<int:pk>', LogDetailView.as_view(), name='log_detail'),
    path('log/create', LogCreateView.as_view(), name='log_create'),
    path('log/<int:pk>/delete', LogDeleteView.as_view(), name='log_delete'),
    path('log/<int:pk>/update', LogUpdateView.as_view(), name='log_update'),

    #model- Board
    path('boards', BoardListView.as_view(), name='board_list'),
    path('board/<int:pk>', BoardDetailView.as_view(), name='board_detail'),
    path('board/create', BoardCreateView.as_view(), name='board_create'),
    path('board/<int:pk>/delete', BoardDeleteView.as_view(), name='board_delete'),
]

logger/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Board(models.Model):
    name = models.CharField(max_length=128)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name


class Topic(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=128)
    description = models.TextField(default="")
    boards = models.ForeignKey(Board, on_delete=models.CASCADE)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return 'Topic: {} | Board: {} | created: {}'.format(self.name, self.boards, self.date)

logger/forms.py
from django import forms
from .models import *


class CreateForm(forms.ModelForm):
    #__init__ ref- https://stackoverflow.com/a/52760176
    def __init__(self, *args, **kwargs):
        users = kwargs.pop('user')
        super(CreateForm, self).__init__(*args, **kwargs)
        self.fields['boards'].queryset = Board.objects.filter(creator=users)
    #datepicker ref- https://stackoverflow.com/a/3368268/8614751
    #forms/widgets ref-https://docs.djangoproject.com/en/3.1/ref/forms/widgets/#styling-widget-instances
    class Meta:
        model = Topic
        fields = ['date', 'name', 'description', 'boards']

    date = forms.DateField(widget=forms.DateInput(attrs=
    	{'id':'datepicker'})
    )
    name = forms.CharField(max_length=128)
    description = forms.CharField(widget=forms.Textarea)

    #forms.ModelChoiceField ref- https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/#field-types
    #objects.filter() ref- https://docs.djangoproject.com/en/3.1/topics/db/queries/#retrieving-all-objects
    boards = forms.ModelChoiceField(queryset=None, widget=forms.Select)

logger/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.views import View
from logger.models import Topic, Board
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from .forms import CreateForm

#Model: Topic
class LogListView(LoginRequiredMixin, View):
	model = Topic
	template_name = 'logger/log_main.html'
	#success_url = reverse_lazy('logger:log_list')
	'''
	def get_queryset(self):
		qs = super(ListView, self).get_queryset()
		return qs.filter(creator=self.request.user)
	'''
	def get(self, request):
		nex = request.path
		topic = Topic.objects.filter(creator=self.request.user)
		bc = Board.objects.filter(creator=self.request.user).count()
		ctx = {'topic_list':topic, 'bc':bc, 'next':nex}
		return render(request, self.template_name, ctx)

class LogDetailView(LoginRequiredMixin, DetailView):
	model = Topic
	template_name = 'logger/log_detail.html'

class LogCreateView(LoginRequiredMixin, View):
	template_name = 'logger/log_form.html'
	success_url = reverse_lazy('logger:log_list')

	def get(self, request, pk=None):
		#args to pass current user details to form
		#request.GET or None- makes sure no pre-errors are shown
		form = CreateForm(request.GET or None, user=request.user)
		ctx={'form':form}
		return render(request, self.template_name, ctx)

	def post(self, request, pk=None):
		form = CreateForm(request.POST, request.FILES or None, user=request.user)
		'''
		if not form.is_valid():
		ctx = {'form':form}
		return render(request, self.template_name, ctx)
		'''
		topic = Topic(date=request.POST['date'], name=request.POST['name'], 
			description=request.POST['description'], creator=request.user, 
			boards=Board.objects.get(pk=request.POST['boards']))
		topic.save()
		return redirect(self.success_url)

class LogUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'logger/log_form.html'
	success_url = reverse_lazy('logger:log_list')

	def get(self, request, pk):
		ob = get_object_or_404(Topic, id=pk, creator=self.request.user)
		form = CreateForm(instance=ob, user=request.user)
		ctx = {'form':form}
		return render(request, self.template_name, ctx)

	def post(self, request, pk=None):
		ob = get_object_or_404(Topic, id=pk, creator=self.request.user)
		form = CreateForm(request.POST, request.FILES or None, instance=ob, user=request.user)

		if not form.is_valid():
			ctx = {'form':form}
			return render(request, self.template_name, ctx)

		ob = form.save(commit=False)
		ob.save()

		return redirect(self.success_url)

class  LogDeleteView(LoginRequiredMixin, DeleteView):
	model = Topic
	template_name = 'logger/log_confirm_delete.html'
	success_url = reverse_lazy('logger:log_list')

	def get_queryset(self):
		qs= super(DeleteView, self).get_queryset()
		return qs.filter(creator=self.request.user)

#Model: Board
class BoardListView(LoginRequiredMixin, ListView):
	model = Board
	template_name = 'logger/board_list.html'

	def get_queryset(self):
		qs = super(ListView, self).get_queryset()
		return qs.filter(creator=self.request.user)

class BoardDetailView(LoginRequiredMixin, View):
	template_name = 'logger/log_main.html'

	def get(self, request, pk):
		bd = Board.objects.get(pk=pk)
		topics = Topic.objects.filter(boards=bd)
		ctx={'topic_list':topics}
		return render(request, self.template_name, ctx)

class BoardCreateView(LoginRequiredMixin, CreateView):
	model = Board
	fields = ['name']
	success_url = reverse_lazy('logger:board_list')

	#get_form() ref- https://docs.djangoproject.com/en/3.1/ref/class-based-views/mixins-editing/#formmixin
	def post(self, request, pk=None):
		form = super(CreateView, self).get_form()
		if not form.is_valid():
			ctx = {'form':form}
			return render(request, self.template_name, ctx)

		fm = form.save(commit=False)
		fm.creator = self.request.user
		fm.save()

		#either next passed by requesting page or board_list page
		try:
			return redirect(self.request.GET['next'])
		except:
			return redirect(self.success_url)

class BoardDeleteView(LoginRequiredMixin, DeleteView):
	model = Board
	template_name = "logger/board_confirm_delete.html"
	success_url = reverse_lazy('logger:board_list')

logger/templates/logger/board_confirm_delete.html
{% extends "base.html" %}
{% block title %}delet?{% endblock %}
{% block content %}
    <div class="container m-5">
    	<h4 class="display-4">Delete board.</h4>
    	<p>Are you sure to delete the board? {{ Board.name }}</p>
    	<form action="" method="post">
    		{% csrf_token %}
    		<input type="submit" value="Yes, Delete">
    		<input type="submit" value="Cancel" onclick="window.location='{% url "logger:board_list" %}'; return false;">
    	</form>
    </div>
{% endblock content %}

logger/templates/logger/board_form.html
{% extends "base.html" %}
{% block title %}boardCreate{% endblock %}

{% block content %}
<div class="container m-5">
	<form action="" method="post">
    	{% csrf_token %}
    	<table>
    	{{ form.as_table }}
    	</table>
    	<input type="submit" value="Submit">
    	<input type="submit" onclick="window.location='{% url 'logger:board_list' %}'; return false;" value="Cancel">
    </form>
</div>
{% endblock content %}

logger/templates/logger/board_list.html
{% extends "base.html" %}
{% block title %}myBoards{% endblock %}
{% block content %}
<div class="container m-5">
    <div class="float-right">
        <p><a href="{% url "logger:board_create" %}" title="">Create board</a> |
            <a href="{% url "logger:log_list" %}">myLogs</a></p>
    </div>
    <h4 class="display-4">Your Boards:</h4>
    {% if board_list %}
    <ul>
    	{% for board in board_list %}
        <li><a class="text-decoration-none" href="{% url "logger:board_detail" board.id %}">{{ board.name }}</a><br>
            &nbsp;&nbsp;<a href="#">Edit</a> |
            <a href="{% url "logger:board_delete" board.id %}">Delete</a></li>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    	<p class="alert alert-info">You don't have any Boards</p>
    {% endif %}
</div>
{% endblock content %}

logger/templates/logger/log_confirm_delete.html
{% extends "base.html" %}
{% block title %}delet?{% endblock %}
{% block content %}
    <div class="container m-5">
    	<h4 class="display-4">Delete log.</h4>
    	<p>Are you sure to delete the log? {{ Topic.name }}</p>
    	<form action="" method="post">
    		{% csrf_token %}
    		<input type="submit" value="Yes, Delete">
    		<input type="submit" value="Cancel" 
    		onclick="window.location='{% url "logger:log_list" %}'; return false;">
    	</form>
    </div>
{% endblock content %}

logger/templates/logger/log_detail.html
{% extends "base.html" %}
{% block title %}log_detail{% endblock %}
{% block content %}
    <div class="container m-5">
    	<span class="float-md-right">
    		<a href="{% url "logger:log_update" topic.id %}">Edit</a> | <a href="{% url "logger:log_delete" topic.id %}">Delete</a> | <a href="{% url "logger:log_list" %}">Back</a></span>
		<p><small>{{ topic.date }}</small></p>
		<h4 class="display-4">{{ topic.name }}</h4><small> from <a class="text-decoration-none" href="{% url "logger:board_list" %}">{{ topic.boards }}</a></small>
		<p>{{ topic.description }}</p>
	</div>
{% endblock content %}

logger/templates/logger/log_form.html
{% extends "base.html" %}
{% block title %}logCreate{% endblock %}
{% block head %}
<!--For date-picker only-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock head %}
{% block content %}
<div class="container m-5">
	<form action="" method="post">
    	{% csrf_token %}
    	<table>
    	{{ form.as_table }}
    	</table>
    	<input type="submit" value="Submit">
    	<input type="submit" value="Cancel"
    	onclick="window.location='{% url 'logger:log_list' %}'; return false;">
    </form>
</div>
{% endblock content %}
{% block script %}
<!-- For date-picker only-->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $(function() {
    $( "#datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "2019:2031",
      dateFormat: 'yy-mm-dd'
      // You can put more options here.

    });
  });
</script>
{% endblock script %}

logger/templates/logger/log_main.html
{% extends "base.html" %}
{% block title %}myLogs{% endblock %}
{% block content %}
    <div class="container m-5">
    	<div class="float-md-right">
    		<p>{% if bc < 1 %}<a href="{% url "logger:board_create" %}?next={{ next }}">Create Board </a>{% else %}<a href="{% url "logger:log_create" %}">Create a Log</a> | <a href="{% url "logger:board_list" %}">Boards</a>{% endif %}</p>
    	</div>
    	<h4 class="display-4">Your Logs:</h4>
        {% if topic_list %}
        <ul>
            {% for topic in topic_list %}
                <li><a class="text-decoration-none" href="{% url "logger:log_detail" topic.id %}">{{ topic.name|title }}</a> - {{ topic.date }}<br>
                    &nbsp;&nbsp;<a href="{% url "logger:log_update" topic.id %}">Edit</a> | 
                    <a href="{% url "logger:log_delete" topic.id %}">Delete</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p class="alert alert-info">You don't have any log {% if bc < 1 %}and board as well{% endif %}</p>
        {% endif %}
    </div>
{% endblock content %}